config/routes.rb
Rails.application.routes.draw do
  resources :quizzes
  # , except: [:new, :edit, :index]
  # get '/new/quiz', to: 'quizzes#new', as: 'new_quiz'
  # get '/edit/quiz/:id', to: 'quizzes#edit', as: 'edit_quiz'
  root 'welcome#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	belongs_to :quiz
	
	validates :content, presence: true, length: {minimum: 1, maximum: 100}
	
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	
	has_many :questions, dependent: :destroy
	
	validates_associated :questions
	
	accepts_nested_attributes_for :questions,
		reject_if: proc { |attributes| attributes['content'].blank? }, allow_destroy: true
	
	validates :title, presence: true, length: {minumim: 3, maximum: 100}
	
	validates_each :questions do |quiz, questions|
		quiz.errors.add questions, "Too many questions." if quiz.questions.length > 6
		quiz.errors.add questions, "Too few questions. (Minimum is 2)" if quiz.questions.length < 2
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @quizzes = Quiz.all
  end

  def show
  end

  def new
    @quiz = Quiz.new
    3.times do
      @quiz.questions.build
    end
  end

  def edit
  end

  def create
    
    @quiz = Quiz.new(quiz_params)

    if @quiz.save
      flash[:success] = "Quiz was created."
      redirect_to @quiz
    else
      flash[:danger] = "Could not save the quiz."
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def quiz_params
      params.require(:quiz).permit(:title, questions_attributes: [:_destroy, :id, :content])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer text-center">
	<br><br>
	A project by Samarth Dave
	<br><br>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, msg| %>
	<div class="alert alert-<%= key %>" role="alert">
		<div class="container text-center">
			<strong><%= msg %></strong>
		</div>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<!--<a href="/" class="pull-left"><img src="/img/logo.png" height="70"></a>-->
			<%= link_to 'QuizApp', root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if !current_page?(controller: '/quizzes', action: 'new') %>
					<li><%= link_to 'New Quiz', new_quiz_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= @title ? @title : 'QuizApp' %></title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= content_tag :body, class: "#{controller_name}-#{action_name}" do %>

  <%= render 'layouts/nav' %>

  <%= yield %>

<% end %>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz, html: {class: 'well'}) do |f| %>
	<% if @quiz.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>
			<ul>
			<% @quiz.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="form-group">
		<%= f.label :title, class: 'sr-only' %><br>
		<%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
	</div>
	<% @count = 0 %>
	<%= f.nested_fields_for :questions do |ff| %>
		<% @count+=1 %>
		<div class="form-group">
			<div class="input-group">
				<% if @count == 1 || @count == 2 %>
					<%= ff.text_field :content, class: 'form-control', placeholder: "Question #{@count}" %>
					<span class="input-group-addon btn btn-danger disabled">
						<span class="fa fa-trash" aria-hidden="true"></span>
					</span>
				<% else %>
					<%= ff.text_field :content, class: 'form-control', placeholder: "Question __nested_field_for_replace_with_index__" %>
					<%= ff.remove_nested_fields_link 'Delete', class: 'btn btn-danger input-group-addon', role: 'button' do %>
						<span class="fa fa-trash" aria-hidden="true"></span>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.add_nested_fields_link :questions, 'Add question', class: 'btn btn-success pull-right', role: 'button' %>
	</div>
	<div class="form-group">
		<%= f.submit class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/quizzes/edit.html.erb
<div class="container">
	<h1>Editing Quiz</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @quiz %>
	
	<%= link_to 'Back', quizzes_path %>

</div>

app/views/quizzes/index.html.erb
<div class="container">
  <h1>Listing Quizzes</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @quizzes.each do |quiz| %>
        <tr>
          <td><%= quiz.title %></td>
          <td><%= link_to 'Show', quiz %></td>
          <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
          <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Quiz', new_quiz_path %>

</div>

app/views/quizzes/new.html.erb
<div class="container">
	<h1>New Quiz</h1>

	<%= render 'form' %>
	
	<%= link_to 'Back', quizzes_path %>

</div>

app/views/quizzes/show.html.erb
<div class="container">
  <p>
    <strong>Title:</strong>
    <%= @quiz.title %>
  </p>
  <p>
    <% @quiz.questions.each do |question| %>
      <p><%= question.content %></p>
    <% end %>
  </p>
  
  <%= link_to 'Edit', edit_quiz_path(@quiz) %> |
  <%= link_to 'Back', quizzes_path %>

</div>

app/views/welcome/index.html.erb
<div class="container">
	<div class="jumbotron text-center">
		<h1>QuizApp</h1>
		<h4>A (free) <i>teacher oriented</i> quiz maker.</h4>
	</div>
</div>

<div class="container">
	<div class="col-md-4 block-list">
		<div class="well b-1">
			<h1 class="midrow text-center">minimal</h1>
			<h4 class="left">our user interface is quick and convenient, available anywhere</h4>
			<p><a class="btn btn-warning btn-small btn-block btn-lg" href="/signup">Sign up now</a></p>
		</div>
	</div>
	<div class="col-md-4 block-list">
		<div class="well b-2">
			<h1 class="midrow text-center">robust</h1>
			<h4 class="left">an unlimited number of questions and custom options for full control</h4>
		</div>
	</div>
	<div class="col-md-4 block-list">
		<div class="well b-3">
			<h1 class="midrow text-center">seamless</h1>
			<h4 class="left">we've build cross platform support so that your content looks great on any device</h4>
		</div>
	</div>
</div>